### PR TITLE
Fix bugs surrounding schedule

### LINKED ISSUE #112: Fix schedule error display message
There should be a space between "and" and "on".
Screenshot 2024-10-26 160040

### LINKED ISSUE #113: Fix error message
Error message could be more specified to say that the months must be between 1-12 and the dates must be between 1-31 (format error)
Screenshot 2024-10-26 162209

### LINKED ISSUE #115: Fix dates invalid input
This should throw an error message that this input is not valid, since 30 Febuary does not exist. Applicable for other months as well where the 31st date might not exist. (invalid input different from format error)
Screenshot 2024-10-26 162437
April 31st does not exist.
Screenshot 2024-10-26 162856

### PR DESCRIPTION
**Pull request by jasmiinee**
Fixes #112 
Fixes #113 
Fixes #115

### CODE REVIEW

File: src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java [hunk 1]
```diff
@@ -53,4 +55,10 @@ public void parse_extraWhitespace_success() {
 
         assertParseSuccess(parser, userInput, expectedCommand);
     }
+
+    @Test
+    public void parse_dateDoNotExist_failure() {
+        String userInput = VALID_NAME + " d/" + NON_EXISTENT_DATE;
+        assertParseFailure(parser, userInput, MESSAGE_INVALID_DATE);
+    }
```
Comment (jiayr99) [inline src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java:63]: LGTM!
